# Start window numbering at 1
set -g base-index 1

# Start pane numbering at 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

# Automatically renumber windows when one is closed
set -g renumber-windows on

# Place status bar on the top
set-option -g status-position top

# Use Tab to cycle down in the choose-tree menu
bind-key -T root Tab if-shell -F '#{==:#{pane_mode},tree-mode}' 'send-keys Down' 'send-keys Tab'

# Use Shift+Tab to cycle up
bind-key -T root BTab if-shell -F '#{==:#{pane_mode},tree-mode}' 'send-keys Up' 'send-keys BTab'

# Bind prefix + @ to visually choose a window to join horizontally
bind-key @ choose-window 'join-pane -h -s "%%"'

# Enable extended keys to recognize modifiers like Shift
set -s extended-keys always
set -s extended-keys-format csi-u

# Pass through the explicit CSI-u sequence for Shift+Enter
bind-key -n S-Enter send-keys -l "\e[13;2u"

# Enable mouse support
set -g mouse on
unbind-key -T copy-mode-vi MouseDragEnd1Pane
unbind-key -T copy-mode MouseDragEnd1Pane
